Validating bags for import
psu-libraries/cho pull request #577
Opened 2018-06-27 20:15 UTC by awead

## Description

Fixes: #561 

Validates the structure and integrity of bags containing one or more works, each will multiple files and file sets.

While it will parse bags of nested works, it doesn't yet validate these if the nested works have errors. This test has been marked pending and can be addressed when nested works are added later.

2018-06-28 16:01 UTC, carolyncole requested changes
@awead overall it looks good.  I'm slightly confused about the concept of Package.  Is that just the top level of the bag?

2018-06-28 16:01 UTC, cam156 commented on app/cho/bag/file.rb
> +    @parts = file.basename(File.extname(file)).to_s.split(/_/)
Using just  '_' is slightly more efficient (and in my mind easier to read)
```
[47] pry(main)> now = DateTime.now; (1..1000).each  {|i|path.basename(File.extname(path)).to_s.split(/_/)}; puts DateTime.now.to_f - now.to_f
0.011595964431762695
=> nil
[48] pry(main)> now = DateTime.now; (1..1000).each  {|i|path.basename(File.extname(path)).to_s.split('_')}; puts DateTime.now.to_f - now.to_f
0.007995843887329102
```

2018-06-28 16:01 UTC, cam156 commented on app/cho/bag/file_validator.rb
> +        return if record.object_id == record.file.parent.basename.to_s
Is this assuming a single file per record?  Is a record a work or a file set?

2018-06-28 16:01 UTC, cam156 commented on app/cho/bag/work.rb
> +  class FileSet
I think this should be in it's own file not relative to the work.

2018-06-28 16:01 UTC, cam156 commented on app/cho/bag/work_validator.rb
> +        if file_set.files.select(&:service?).empty? && file_set.files.select(&:preservation?).empty?
How dose a representative relate to service and preservation?  Can yo have all 3? If there is a service and a preservation, but no representative should an error be produced?

2018-06-28 16:01 UTC, cam156 commented on spec/cho/bag/package_spec.rb
> +          objectID: [
These look like file names, not objectIDs

2018-06-28 16:01 UTC, cam156 commented on spec/cho/bag/work_spec.rb
> +        objectID: [
Are these really objects?

2018-06-29 11:02 UTC, awead commented on app/cho/bag/file.rb
> +    @parts = file.basename(File.extname(file)).to_s.split(/_/)
@cam156 huh. I never knew you could pass a string to `split`. I always thought it had to be a regex.

2018-06-29 11:09 UTC, awead commented on app/cho/bag/file_validator.rb
> +        return if record.object_id == record.file.parent.basename.to_s
`record` here is a file, or `Bag::File`. I was thinking about re-configuring the validations so that they were methods inside the class they're validating, rather than separate classes. That might make it easer to understand. Something like:
``` ruby
class Bag::File
  validate :object_id_must_match_parent

  def object_id_must_match_parent
    return if object_id == file.parent.basename.to_s
    errors.add(:file, "blah....")
  end

end

2018-06-29 11:10 UTC, awead commented on app/cho/bag/work.rb
> +  class FileSet
@cam156 I thought about that, but it seemed to over-complicate things. If it is, should there be separate unit tests as well?

2018-06-29 11:14 UTC, awead commented on app/cho/bag/work_validator.rb
> +        if file_set.files.select(&:service?).empty? && file_set.files.select(&:preservation?).empty?
@cam156 A representative isn't a file type. It's an unnamed type of FileSet. The distinction is drawn by looking at all the files in the set. If none of them have an id segment, it's a representative file set, i.e. it's representative of the work. There's an example [here](https://github.com/psu-libraries/cho/wiki/File-Specifications#simple-work-folder-of-manuscript-materials) where there's a file set that has the pdf of all the pages, and separate file sets for each individual page.

2018-06-29 11:15 UTC, awead commented on spec/cho/bag/package_spec.rb
> +          objectID: [
It's the directory name. I chose a hash structure because it seemed to best reflect the directory structures in https://github.com/psu-libraries/cho/wiki/File-Specifications

2018-06-29 11:16 UTC, awead commented on spec/cho/bag/work_spec.rb
> +        objectID: [
@cam156 not exactly. They'll be works when they're imported. I was following the examples in the specification, but `workID` might be a lot clearer.

2018-06-29 11:20 UTC, awead commented
@cam156 the package is the bag. I needed another noun to reflect what our bags were, otherwise it would be `Bag::Bag`. I'm open to other suggestions.

2018-06-29 11:55 UTC, cam156 commented on app/cho/bag/file_validator.rb
> +        return if record.object_id == record.file.parent.basename.to_s
@awead I wonder if this is another opportunity for dry-transactions?

2018-06-29 11:57 UTC, cam156 commented
@awead paper? 😄 Does it represent a a work at the top level or a List or Works?

2018-06-29 12:41 UTC, awead commented on app/cho/bag/file_validator.rb
> +        return if record.object_id == record.file.parent.basename.to_s
@cam156 we could, but we wouldn't get the `valid?` method, unless we want the transaction to call that. I can definitely see dry-transactions for the actual ingest/import, in which case a valid operation would call `valid?` on the bag and report the errors accordingly. The nice thing about AR validations is you get the `valid?` method and the `errors` object.

2018-07-02 10:36 UTC, carolyncole approved these changes

2018-07-02 10:36 UTC, merged